version: '3'
services:
  app:
    image : meeting-video-helper
    build: .
    container_name: meeting-video-helper
    ports: 
      - 9528:8080 
    depends_on:
      - db
    restart: always
    networks:
      - server
  db:
    image: mongo
    container_name: mongodb
    ports:
      - '27018:27017'
    command: ["--auth", "--bind_ip_all"]
    volumes:
      - mongodb-volume:/var/lib/mysql:/app/database/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    restart: always
    networks:
      - server
volumes:
  mongodb-volume:
networks:
  server: