version: '3'
services:
  app:
    image : meeting-video-helper
    build: .
    container_name: meeting-video-helper
    ports: 
      - 9528:9528
    depends_on:
      - db
    restart: on-failure
    networks:
      - server
  db:
    image: mongo
    container_name: mongodb
    ports:
      - '27018:27017'
    command: ["--auth", "--bind_ip_all"]
    volumes:
      - mongodb-volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    restart: on-failure
    networks:
      - server
  redis:
    container_name: "redis"
    image: redis:alpine
    # Specify the redis.conf file to use and add a password.
    command: redis-server /usr/local/etc/redis/redis.conf
    # 如果要透過yaml對Redis設置密碼
    # command: redis-server /usr/local/etc/redis/redis.conf --requirepass mypassword
    ports: 
      - "6379:6379"
    # map the volumes to that redis has the custom conf file from this project.
    volumes: 
      - /redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - server
volumes:
  mongodb-volume:
networks:
  server: